name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update dependencies
      run: |
        npm update
        npm audit fix --audit-level=high
        
    - name: Run tests
      run: |
        npm run lint
        npm run type-check
        npm run build
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: Automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates:
          
          - Updated npm dependencies to latest versions
          - Fixed security vulnerabilities (if any)
          - Verified build and type checking passes
          
          ### Changes Made:
          - `npm update` - Updated all dependencies to latest compatible versions
          - `npm audit fix` - Fixed high-severity vulnerabilities
          
          ### Verification:
          - ✅ Linting passes
          - ✅ Type checking passes  
          - ✅ Build successful
          
          **Note:** This PR was automatically created by GitHub Actions.
          Please review the changes before merging.
        branch: chore/dependency-updates
        branch-suffix: timestamp
        delete-branch: true
        
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"